[tox]
envlist = py, codestyle
skipsdist = True

[testenv]
deps =
    pytest
    jsonpickle>=3.0.0
    redis
    fakeredis
    errbot
commands = pytest -v

[testenv:codestyle]
deps =
    ruff
    isort
commands =
    ruff check redisstorage.py test_redis.py
    ruff format --check redisstorage.py test_redis.py
    isort --check-only redisstorage.py test_redis.py
